version: "3.8"

services:
  postgres-smart-loader:
    container_name: postgres-smart-loader
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure
    env_file:
      - .env
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./.docker-volumes/postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pre_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      smart-loader-net:
        ipv4_address: 172.28.1.1

  liquibase-smart-loader:
    container_name: liquibase-smart-loader
    image: liquibase/liquibase:${LIQUIBASE_VERSION}
    restart: on-failure
    command: --defaultsFile=liquibase.properties update
    depends_on:
      - postgres-smart-loader
    volumes:
      - ./migration/:/liquibase/changelog/
      - ./migration/:/liquibase/classpath/
      - ./migration/liquibase.properties:/liquibase/liquibase.properties
    networks:
      smart-loader-net:
        ipv4_address: 172.28.1.2

  nats-smart-loader:
    container_name: nats-smart-loader
    image: nats:${NATS_VERSION}
    restart: on-failure
    ports:
      - ${NATS_HTTP_PORT}:8222
      - ${NATS_PORT}:4222
    networks:
      smart-loader-net:
        ipv4_address: 172.28.1.3

networks:
  smart-loader-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16