// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency

import (
	"github.com/tuxoo/smart-loader/facade-service/internal/config"
)

// Injectors from wire.go:

func InitConfig() (*config.Config, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}
