CREATE SCHEMA IF NOT EXISTS smart_loader;

CREATE TABLE "user"
(
    id            bigint generated by default as identity primary key,
    name          varchar(255)        not null,
    login_email   varchar(255) unique not null,
    password_hash varchar(255)        not null,
    registered_at timestamp           not null,
    visited_at    timestamp           not null
);

INSERT INTO "user" (name, login_email, password_hash, registered_at, visited_at)
VALUES ('admin', 'admin@admin', 'qwerty', now(), now());

CREATE TABLE job
(
    id         uuid default gen_random_uuid() primary key,
    name       varchar(32)                   not null,
    size       bigint                        not null,
    status     varchar(32)                   not null,
    created_at timestamp                     not null,
    user_id    bigint
        constraint fk_user references "user" not null
);

CREATE TABLE job_stage
(
    id     bigint generated by default as identity primary key,
    size   bigint                        not null,
    uris   text[] not null,
    status varchar(32)                   not null,
    job_id uuid
        constraint fk_job references job not null
);

CREATE TABLE download
(
    id            uuid default gen_random_uuid() primary key,
    hash          varchar(64) unique not null,
    downloaded_at timestamp          not null
);