http:
  host: localhost
  port: 9000
  maxHeaderMegabytes: 1
  readTimeout: 5s
  writeTimeout: 10s

postgres:
  host: localhost
  port: 5432
  dbname: smart_loader
  maxConns: 25
  minConns: 2
  maxConnLifetime: 120s
  maxConnIdleTime: 300s

nats:
  port: 4222

app:
  uriPartitionSize: 3
  tokenTtl: 180m