http:
  host: localhost
  port: 8080
  maxHeaderMegabytes: 1
  readTimeout: 5s
  writeTimeout: 10s

postgres:
  host: localhost
  port: 5432
  dbname: smart_loader
  maxConns: 25
  minConns: 2
  maxConnLifetime: 120s
  maxConnIdleTime: 300s

nats:
  port: 4222

minio:
  endpoint:

app:
  uriPartitionSize: 3
  tokensLimit: 3
  accessTokenTtl: 10m
  refreshTokenTtl: 72h